name: release-solution-to-prod
# prepare for releasing to prod:
#   convert solution to managed (using a build PowerPlatform environment for the conversion)
#   upload the solution to the GitHub artifacts and deploy to the PROD environment

on:
  push:
    branches: [ main ]

env:
#edit your values here
  BUILD_ENVIRONMENT_URL: https://orga0143a4d.crm.dynamics.com
  PRODUCTION_ENVIRONMENT_URL: https://org204ad4c8.crm.dynamics.com/
  APP_ID: b5f789c3-3066-473e-b03e-b8e22f4ba987
  TENANT_ID: 54a8e544-1927-4edb-8e84-4225ed8e739a
  SOLUTION_NAME: eKnowArquitectura

jobs:
  convert-to-managed:
    runs-on: windows-latest
    env:
      RUNNER_DEBUG: 1

    steps:
    - uses: actions/checkout@v2
      with:
        lfs: true

    - name: Export solution as managed
      uses: microsoft/powerplatform-actions/export-solution@0.4.0
      with:
        environment-url: ${{env.BUILD_ENVIRONMENT_URL}}
        app-id: ${{env.APP_ID}}
        client-secret: ${{ secrets.SECRETO_DE_CUENTA_DE_SERVICIO_POWERAPPS }}
        tenant-id: ${{env.TENANT_ID}}
        solution-name: ${{ env.SOLUTION_NAME }}
        managed: true
        solution-output-file: out/ship/${{ env.SOLUTION_NAME }}.zip

    - name: Upload the ready to ship solution to GH artifact store
      uses: actions/upload-artifact@v2
      with:
        name: managedSolutions
        path: out/ship/${{ env.SOLUTION_NAME }}.zip

  release-to-production:
    needs: [ convert-to-managed ]
    runs-on: windows-latest
    env:
      RUNNER_DEBUG: 1

    steps:
    - uses: actions/checkout@v2
      with:
        lfs: true

    - name: Fetch the ready to ship solution from GH artifact store
      uses: actions/download-artifact@v2
      with:
        name: managedSolutions
        path: out/release/

    - name: Import solution to prod env
      uses: microsoft/powerplatform-actions/import-solution@0.4.0
      with:
        environment-url: ${{env.PRODUCTION_ENVIRONMENT_URL}}
        app-id: ${{env.APP_ID}}
        client-secret: ${{ secrets.SECRETO_DE_CUENTA_DE_SERVICIO_POWERAPPS }}
        tenant-id: ${{env.TENANT_ID}}
        solution-file: out/release/${{ env.SOLUTION_NAME }}.zip
        force-overwrite: true
        publish-changes: true
